import { z } from "zod";
/**
 * Tools generated by mcpfoundry from a openapi source.
 * Each tool ships a Zod schema (parameter hardening, always on) and a working
 * handler (HTTP call to BASE_URL).
 */
export interface McpTool {
  name: string;
  description: string;
  schema: Record<string, z.ZodTypeAny>;
  handler: (args: any) => Promise<{ content: { type: "text"; text: string }[] }>;
}

export const tools: McpTool[] = [
  {
    name: "list_pets",
    description: "List all pets",
    schema: {
      limit: z.number().int().describe("Maximum number of pets to return").optional(),
    },
    handler: async (args) => {
      const base = process.env.BASE_URL ?? "";
      let path = "/pets";
      const url = new URL(base + path);
      if (args.limit !== undefined) url.searchParams.set("limit", String(args.limit));
      const headers: Record<string, string> = { Accept: "application/json" };
      if (process.env.API_AUTH) headers.Authorization = process.env.API_AUTH;
      const res = await fetch(url.toString(), { method: "GET", headers });
      const text = "[" + res.status + "] " + (await res.text());
      return { content: [{ type: "text", text: text }] };
    },
  },
  {
    name: "create_pet",
    description: "Create a pet",
    schema: {
      name: z.string().describe("The pet's name"),
      tag: z.string().describe("An optional tag").optional(),
    },
    handler: async (args) => {
      const base = process.env.BASE_URL ?? "";
      let path = "/pets";
      const url = new URL(base + path);
      const headers: Record<string, string> = { Accept: "application/json" };
      if (process.env.API_AUTH) headers.Authorization = process.env.API_AUTH;
      headers["Content-Type"] = "application/json";
      const payload: Record<string, unknown> = {};
      if (args.name !== undefined) payload["name"] = args.name;
      if (args.tag !== undefined) payload["tag"] = args.tag;
      const res = await fetch(url.toString(), { method: "POST", headers, body: JSON.stringify(payload) });
      const text = "[" + res.status + "] " + (await res.text());
      return { content: [{ type: "text", text: text }] };
    },
  },
  {
    name: "get_pet_by_id",
    description: "Fetch a pet by ID",
    schema: {
      pet_id: z.number().int().describe("ID of the pet to fetch"),
    },
    handler: async (args) => {
      const base = process.env.BASE_URL ?? "";
      let path = "/pets/{petId}";
      path = path.replace("{petId}", encodeURIComponent(String(args.pet_id)));
      const url = new URL(base + path);
      const headers: Record<string, string> = { Accept: "application/json" };
      if (process.env.API_AUTH) headers.Authorization = process.env.API_AUTH;
      const res = await fetch(url.toString(), { method: "GET", headers });
      const text = "[" + res.status + "] " + (await res.text());
      return { content: [{ type: "text", text: text }] };
    },
  },
  {
    name: "delete_pet",
    description: "Delete a pet by ID",
    schema: {
      pet_id: z.number().int().describe("ID of the pet to delete"),
    },
    handler: async (args) => {
      const base = process.env.BASE_URL ?? "";
      let path = "/pets/{petId}";
      path = path.replace("{petId}", encodeURIComponent(String(args.pet_id)));
      const url = new URL(base + path);
      const headers: Record<string, string> = { Accept: "application/json" };
      if (process.env.API_AUTH) headers.Authorization = process.env.API_AUTH;
      const res = await fetch(url.toString(), { method: "DELETE", headers });
      const text = "[" + res.status + "] " + (await res.text());
      return { content: [{ type: "text", text: text }] };
    },
  },
];
